# Generated by Django 6.0.5 on 2026-05-11 20:24

import django.core.validators
import participants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_lastname', models.CharField(max_length=100)),
                ('mother_lastname', models.CharField(max_length=100)),
                ('names', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dni_number', models.CharField(max_length=8, unique=True)),
                ('orcid_number', models.CharField(blank=True, max_length=19, null=True)),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('dni_document', models.FileField(help_text='Adjuntar PDF del DNI', upload_to='documents/dni/', validators=[participants.models.validate_pdf])),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['father_lastname', 'mother_lastname'],
            },
        ),
    ]
