# Generated by Django 6.0.5 on 2026-05-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicViewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public_enabled', models.BooleanField(default=True)),
                ('visibility_mode', models.CharField(choices=[('PUBLIC', 'Público - Cualquier persona puede ver'), ('PRIVATE', 'Privado - Solo participantes registrados'), ('PROTECTED', 'Protegido - Requiere código de acceso')], default='PUBLIC', max_length=20)),
                ('access_code', models.CharField(blank=True, max_length=20, null=True)),
                ('show_participant_info', models.BooleanField(default=True)),
                ('show_payment_info', models.BooleanField(default=False)),
                ('allow_product_search', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Vista Pública',
                'verbose_name_plural': 'Configuraciones de Vista Pública',
            },
        ),
    ]
