# Generated by Django 6.0.5 on 2026-05-11 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('REGISTERED', 'Registrado'), ('OBSERVED', 'Observado'), ('IN_PROCESS', 'En Proceso'), ('COMPLETED', 'Finalizado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
                ('is_payment_exempt', models.BooleanField(default=False)),
                ('exemption_reason', models.TextField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('product', 'participant')},
            },
        ),
    ]
